ALTER TABLE Compradores ADD CONSTRAINT chk_idComprador CHECK (REGEXP_LIKE(idPersona, '^CDR-[0-9]{5}$'));
ALTER TABLE Compradores ADD CONSTRAINT chk_idCompra_Comprador CHECK (REGEXP_LIKE(idCompra, '^COM-[0-9]{5}$'));
ALTER TABLE Personas ADD CONSTRAINT chk_tipoPersona CHECK (tipoPersona IN ('comprador', 'vendedor'));
ALTER TABLE Vendedores ADD CONSTRAINT chk_idVendedor CHECK (REGEXP_LIKE(idPersona, '^VEN-[0-9]{5}$'));
ALTER TABLE Vendedores ADD CONSTRAINT chk_idAutomovil_Vendedor CHECK (REGEXP_LIKE(idAutomovil, '^AUT-[0-9]{5}$'));
ALTER TABLE Vendedores ADD CONSTRAINT chk_esConcecionario CHECK (esConcecionario IN ('Si', 'No'));
ALTER TABLE Talleres ADD CONSTRAINT chk_idTaller CHECK (REGEXP_LIKE(idTaller, '^TAL-[0-9]{5}$'));
ALTER TABLE Talleres ADD CHECK (REGEXP_LIKE(idPieza, '^PIE-[0-9]{5}$'));
ALTER TABLE Talleres ADD CHECK (REGEXP_LIKE(idBodega, '^BOD-[0-9]{5}$'));
ALTER TABLE Homologaciones ADD CONSTRAINT chk_idHomologacion CHECK (REGEXP_LIKE(idHomologacion, '^HOM-[0-9]{5}$'));
ALTER TABLE Homologaciones ADD CONSTRAINT chk_idAuto CHECK (REGEXP_LIKE(idAuto, '^AUT-[0-9]{5}$'));
ALTER TABLE Vendedores ADD CONSTRAINT chk_idVendedores CHECK (REGEXP_LIKE(idPersona, '^VEN-[0-9]{5}$'));
ALTER TABLE Compras ADD CONSTRAINT chk_idComprador_Compra CHECK (REGEXP_LIKE(idComprador, '^CDR-[0-9]{5}$'));
ALTER TABLE Compras ADD CONSTRAINT chk_formaPago CHECK (formaPago IN ('transferencia', 'Deposito', 'efectivo'));
ALTER TABLE Compras ADD CONSTRAINT chk_estadoPago CHECK (estadoPago IN ('Realizado', 'En tramite'));
ALTER TABLE Facturas ADD CONSTRAINT chk_idFactura CHECK (REGEXP_LIKE(idFactura, '^FAC-[0-9]{5}$'));
ALTER TABLE Automoviles ADD CONSTRAINT chk_papelesTramite CHECK (papelesEnTramite IN ('Si', 'No'));
ALTER TABLE Automoviles ADD CONSTRAINT chk_placa CHECK (REGEXP_LIKE(placa, '^[A-Z]{3} [0-9]{3}$'));
ALTER TABLE Automoviles ADD CONSTRAINT chk_garantiaAutomovil CHECK (REGEXP_LIKE(garantiaAutomovil, '^[0-9]{2} meses$'));
ALTER TABLE Proveedores ADD CONSTRAINT chk_calificacion CHECK (calificacion BETWEEN 0 AND 5);
ALTER TABLE Proveedores ADD CONSTRAINT chk_idProveedor CHECK (REGEXP_LIKE(idProveedor, '^PRO-[0-9]{5}$'));
ALTER TABLE Pedidos ADD CONSTRAINT chk_idPedido CHECK (REGEXP_LIKE(idPedido, '^PED-[0-9]{5}$'));
ALTER TABLE Pedidos ADD CONSTRAINT chk_pedidos_estado CHECK (estadoPedido IN ('retrasado', 'entregado', 'saliendo', 'en camino'));
ALTER TABLE TramitesAduanas ADD CONSTRAINT chk_idTramite CHECK (REGEXP_LIKE(idTramite, '^TRA-[0-9]{5}$'));
ALTER TABLE Piezas ADD CONSTRAINT chk_idPieza CHECK (REGEXP_LIKE(idPieza, '^PIE-[0-9]{5}$'));
ALTER TABLE Piezas ADD CONSTRAINT chk_garantiaPieza CHECK (REGEXP_LIKE(garantiaPieza, '^[0-9]{2} meses$'));
ALTER TABLE Inventarios ADD CONSTRAINT chk_Testante CHECK (REGEXP_LIKE(Testante, '^[A-Z][0-9]$'));
ALTER TABLE Inventarios ADD CONSTRAINT chk_TidPiezaInv CHECK (REGEXP_LIKE(TidPieza, '^PIE-[0-9]{5}$'));
ALTER TABLE Inventarios ADD CONSTRAINT chk_TidBodegaInv CHECK (REGEXP_LIKE(TidBodega, '^BOD-[0-9]{5}$'));
ALTER TABLE Contienen ADD CONSTRAINT chk_idPedidoContiene CHECK (REGEXP_LIKE(idPedido, '^PED-[0-9]{5}$'));
ALTER TABLE Contienen ADD CONSTRAINT chk_idPiezaContiene CHECK (REGEXP_LIKE(idPieza, '^PIE-[0-9]{5}$'));
ALTER TABLE CarrosInteresado ADD CONSTRAINT chk_idPersonaCarrosInteresado CHECK (REGEXP_LIKE(idPersona, '^CDR-[0-9]{5}$'));
ALTER TABLE PiezasInteresado ADD CONSTRAINT chk_idPersonaPiezasInteresado CHECK (REGEXP_LIKE(idPersona, '^CDR-[0-9]{5}$'));
ALTER TABLE CarrosComprados ADD CONSTRAINT chk_idPersonaCarrosComprados CHECK (REGEXP_LIKE(idPersona, '^CDR-[0-9]{5}$'));
ALTER TABLE CarrosOfrece ADD CONSTRAINT chk_idPersonaCarrosOfrece CHECK (REGEXP_LIKE(idPersona, '^VEN-[0-9]{5}$'));
ALTER TABLE AutosCompatibles ADD CONSTRAINT chk_idPiezaAutosCompatibles CHECK (REGEXP_LIKE(idPieza, '^PIE-[0-9]{5}$'));
ALTER TABLE CompraAutos ADD CONSTRAINT chk_idCompraAutos CHECK (REGEXP_LIKE(idCompra, '^COM-[0-9]{5}$'));
ALTER TABLE CompraAutos ADD CONSTRAINT chk_idAutoCompraAutos CHECK (REGEXP_LIKE(idAuto, '^AUT-[0-9]{5}$'));
ALTER TABLE CompraPiezas ADD CONSTRAINT chk_idCompraPiezas CHECK (REGEXP_LIKE(idCompra, '^COM-[0-9]{5}$'));
ALTER TABLE CompraPiezas ADD CONSTRAINT chk_idPiezaCompraPiezas CHECK (REGEXP_LIKE(idPieza, '^PIE-[0-9]{5}$'));
