ALTER TABLE Personas ADD CONSTRAINT pk_Personas PRIMARY KEY (idPersona);
ALTER TABLE Compradores ADD CONSTRAINT pk_comprador PRIMARY KEY (idPersona);
ALTER TABLE Vendedores ADD CONSTRAINT pk_vendedor PRIMARY KEY (idPersona);
ALTER TABLE Talleres ADD CONSTRAINT pk_Talleres PRIMARY KEY (idTaller);
ALTER TABLE Homologaciones ADD CONSTRAINT pk_Homologaciones PRIMARY KEY (idHomologacion);
ALTER TABLE Compras ADD CONSTRAINT pk_compra PRIMARY KEY (idCompra);
ALTER TABLE Facturas ADD CONSTRAINT pk_factura PRIMARY KEY (idFactura);
ALTER TABLE Importaciones ADD CONSTRAINT pk_importacion PRIMARY KEY (idImportacion);
ALTER TABLE Automoviles ADD CONSTRAINT pk_automoviles PRIMARY KEY (idAutomovil);
ALTER TABLE Proveedores ADD CONSTRAINT pk_proveedor PRIMARY KEY (idProveedor);
ALTER TABLE Pedidos ADD CONSTRAINT pk_pedidos PRIMARY KEY (idPedido);
ALTER TABLE TramitesAduanas ADD CONSTRAINT pk_tramitesaduanas PRIMARY KEY (idTramite);
ALTER TABLE Piezas ADD CONSTRAINT pk_pieza PRIMARY KEY (idPieza);
ALTER TABLE Inventarios ADD CONSTRAINT pk_inventario PRIMARY KEY (idBodega);
ALTER TABLE HistorialMantenimientos ADD CONSTRAINT pk_HistorialMantenimientos PRIMARY KEY (idMantenimiento);
ALTER TABLE Contienen ADD CONSTRAINT pk_Contienen PRIMARY KEY (idPedido, idPieza);
ALTER TABLE CarrosInteresado ADD CONSTRAINT pk_carrosinteresado PRIMARY KEY (idPersona, carroInteresado);
ALTER TABLE PiezasInteresado ADD CONSTRAINT pk_piezasinteresado PRIMARY KEY (idPersona, piezaInteresado);
ALTER TABLE CarrosComprados ADD CONSTRAINT pk_carroscomprados PRIMARY KEY (idPersona, carroComprado);
ALTER TABLE CarrosOfrece ADD CONSTRAINT pk_carrossofrece PRIMARY KEY (idPersona, carroOfrece);
ALTER TABLE AutosCompatibles ADD CONSTRAINT pk_autoscompatibles PRIMARY KEY (idPieza, autoCompatible);
ALTER TABLE CompraAutos ADD CONSTRAINT pk_CompraAutos PRIMARY KEY (idCompra, idAuto);
ALTER TABLE CompraPiezas ADD CONSTRAINT pk_CompraPiezas PRIMARY KEY (idCompra, idPieza);
